#!/bin/sh

# $FreeBSD: branches/2019Q1/ftp/tftp-hpa/files/tftpd.in 340872 2014-01-24 00:14:07Z mat $
#
# PROVIDE: tftpd
# REQUIRE: NETWORKING
# KEYWORD: shutdown
#
# Add the following line to /etc/rc.conf to enable tftpd:
#
# tftpd_enable="YES"
#

. /etc/rc.subr

name="tftpd"
rcvar=tftpd_enable
pidfile=${tftpd_pidfile:-"/var/run/tftpd.pid"}
command="/usr/local/libexec/in.tftpd"
command_args="-P $pidfile -l"

load_rc_config $name
: ${tftpd_enable:="NO"}
: ${tftpd_flags:="-s /tftpboot -m /tftpboot/remap"}

run_rc_command "$1"
